### ISSUE TITLE
add mathjax-node dependency to package.json?

### ISSUE THREAD

**Issue by Pomax** [tiarno/mathjax-server#1]
Since this depends on mathjax-node, the simplest way to get that in is to say `npm install mathjax-node --save`, so that npm updates your mathjax-server package.json with the required dependency, and then people won't have to manually install mathjax-node themselves anymore.

**Comment by tiarno** [comment]
Thanks for the comment--I'd be glad to make that change. I believe this should do it; do you agree?
    
    { "dependencies": { "mathjax-node": "latest" } }

**Comment by Pomax** [comment]
just to make sure you don't auto-update on major version changes (which are API breaking by convention), use `npm install mathjax-node --save` and it should automatically create the following:
```
{
 ...
  "dependencies": {
    "mathjax-node": "^0.4.0"
  }
 ...
}
```
The `^` indicates "any version this or higher, for minor/patch changes only"

**Comment by tiarno** [comment]
Thanks, I just updated it. That should make it easier to use.

**Comment by Pomax** [comment]
awesome, thanks!
